backend:
  name: github
  repo: dnwk/w7dp-website
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://w7dp-oauth.herokuapp.com/
  #auth_endpoint: api/auth
#local_backend: true
# These lines should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Blog"
    name: "blog"
    folder: "w7dp/content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    folder: "w7dp/content/pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Homepage"
    label: "homepage"
    create: false
    slug: "{{slug}}"
    files:
      - file: "w7dp/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
